name: SimpleHub
main: net.codekrafter.plugins.simplehub.SimpleHub
version: 0.0.1
commands:
    testcolorcmd:
          description: This is a demo command, for testing color parsing, will retrun the message you give it, all formatted.
          usage: /testcolorcmd <message>
    setinhub:
          description: sets wether or not a player is "in the hub"
          usage: /setinhub <player> <true/false>