name: SimpleHub
main: net.codekrafter.plugins.simplehub.SimpleHub
version: 1.0.0
authors: ["codekrafter"]
commands:
    sh:
          description: The Base Simple Hub Command
          usage: /sh <subcommands>
    simplehub:
          description: The Base Simple Hub Command
          usage: /simplehub <subcommands>
    simpleh:
          description: The Base Simple Hub Command
          usage: /simpleh <subcommands>
    shub:
          description: The Base Simple Hub Command
          usage: /shub <subcommands>
#    pvp:
#          description: Toggles PvP
#          usage: /pvp